# Generated by Django 5.0.6 on 2026-06-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nivel de Formación',
                'verbose_name_plural': 'Niveles de Formación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facultades', to='institucional.campus')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_academicos', to='institucional.facultad')),
                ('nivel_formacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_academicos', to='institucional.nivelformacion')),
            ],
            options={
                'verbose_name': 'Programa Académico',
                'verbose_name_plural': 'Programas Académicos',
                'ordering': ['nombre'],
            },
        ),
    ]
