# Generated by Django 5.0.6 on 2026-06-19 02:39

import matricula.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(max_length=500, upload_to=matricula.models.ruta_documento_adjunto)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Documento Adjunto',
                'verbose_name_plural': 'Documentos Adjuntos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(max_length=500, upload_to=matricula.models.ruta_matricula_oficial)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matrícula Oficial',
                'verbose_name_plural': 'Matrículas Oficiales',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('no_publicado', 'No publicado'), ('publicado', 'Publicado')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periodo de Matrícula',
                'verbose_name_plural': 'Periodos de Matrícula',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('PDF/JPG', 'PDF/JPG')], max_length=10)),
            ],
            options={
                'verbose_name': 'Requisito Documental',
                'verbose_name_plural': 'Requisitos Documentales',
                'ordering': ['periodo_matricula', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Asignatura Solicitada',
                'verbose_name_plural': 'Asignaturas Solicitadas',
            },
        ),
        migrations.CreateModel(
            name='SolicitudMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_intento', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente_revision', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Matrícula',
                'verbose_name_plural': 'Solicitudes de Matrícula',
                'ordering': ['-created_at'],
            },
        ),
    ]
