# Generated by Django 5.0.6 on 2026-06-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('matricula', '0001_initial'),
        ('programacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaoficial',
            name='jefe_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_oficiales_generadas', to='usuarios.jefedepartamento'),
        ),
        migrations.AddField(
            model_name='periodomatricula',
            name='jefe_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_matricula', to='usuarios.jefedepartamento'),
        ),
        migrations.AddField(
            model_name='periodomatricula',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_matricula', to='academico.periodoacademico'),
        ),
        migrations.AddField(
            model_name='requisitodocumental',
            name='periodo_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitos_documentales', to='matricula.periodomatricula'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='requisito_documental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_adjuntos', to='matricula.requisitodocumental'),
        ),
        migrations.AddField(
            model_name='solicitudasignatura',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asignatura', to='programacion.grupo'),
        ),
        migrations.AddField(
            model_name='solicitudmatricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_matricula', to='usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='solicitudmatricula',
            name='periodo_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_matricula', to='matricula.periodomatricula'),
        ),
        migrations.AddField(
            model_name='solicitudasignatura',
            name='solicitud_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_solicitadas', to='matricula.solicitudmatricula'),
        ),
        migrations.AddField(
            model_name='matriculaoficial',
            name='solicitud_matricula',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='matricula_oficial', to='matricula.solicitudmatricula'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='solicitud_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_adjuntos', to='matricula.solicitudmatricula'),
        ),
        migrations.AddConstraint(
            model_name='solicitudasignatura',
            constraint=models.UniqueConstraint(fields=('solicitud_matricula', 'grupo'), name='uk_solicitud_grupo'),
        ),
    ]
