# Generated by Django 5.0.6 on 2026-06-22 16:16

import cloudinary_storage.storage
import matricula.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadjunto',
            name='archivo',
            field=models.FileField(max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=matricula.models.ruta_documento_adjunto),
        ),
        migrations.AlterField(
            model_name='matriculaoficial',
            name='documento',
            field=models.FileField(max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=matricula.models.ruta_matricula_oficial),
        ),
    ]
