# Generated by Django 5.0.6 on 2026-06-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_alter_documentoadjunto_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmatricula',
            name='enviada_formalmente',
            field=models.BooleanField(default=False),
        ),
    ]
