# Generated by Django 5.0.6 on 2026-06-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('solicitud_recibida', 'Solicitud recibida'), ('solicitud_aprobada', 'Solicitud aprobada'), ('solicitud_rechazada', 'Solicitud rechazada'), ('matricula_generada', 'Matrícula generada'), ('fecha_limite_proxima', 'Fecha límite próxima')], max_length=30)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
