# Generated by Django 5.0.6 on 2026-06-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('institucional', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialacademico',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_academico', to='usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_academico', to='academico.periodoacademico'),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='programa_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='institucional.programaacademico'),
        ),
        migrations.AddField(
            model_name='planestudioasignatura',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_asignatura', to='academico.asignatura'),
        ),
        migrations.AddField(
            model_name='planestudioasignatura',
            name='plan_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_plan', to='academico.planestudio'),
        ),
        migrations.AddField(
            model_name='prerrequisito',
            name='asignatura',
            field=models.ForeignKey(help_text='Asignatura que exige el prerrequisito', on_delete=django.db.models.deletion.CASCADE, related_name='prerrequisitos', to='academico.asignatura'),
        ),
        migrations.AddField(
            model_name='prerrequisito',
            name='asignatura_prerrequisito',
            field=models.ForeignKey(help_text='Asignatura que debe haberse aprobado antes', on_delete=django.db.models.deletion.CASCADE, related_name='es_prerrequisito_de', to='academico.asignatura'),
        ),
        migrations.AddConstraint(
            model_name='historialacademico',
            constraint=models.UniqueConstraint(fields=('estudiante', 'asignatura', 'periodo_academico'), name='uk_historial_estudiante_asignatura_periodo'),
        ),
        migrations.AddConstraint(
            model_name='planestudioasignatura',
            constraint=models.UniqueConstraint(fields=('plan_estudio', 'asignatura'), name='uk_plan_asignatura'),
        ),
        migrations.AddConstraint(
            model_name='prerrequisito',
            constraint=models.UniqueConstraint(fields=('asignatura', 'asignatura_prerrequisito'), name='uk_asignatura_prerrequisito'),
        ),
    ]
