# Generated by Django 5.0.6 on 2026-06-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('institucional', '0001_initial'),
        ('programacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='horariogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='programacion.grupo'),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='jefe_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_academicas', to='usuarios.jefedepartamento'),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_academicas', to='academico.periodoacademico'),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='programa_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_academicas', to='institucional.programaacademico'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='programacion_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='programacion.programacionacademica'),
        ),
        migrations.AddField(
            model_name='salon',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salones', to='institucional.campus'),
        ),
        migrations.AddField(
            model_name='horariogrupo',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='programacion.salon'),
        ),
        migrations.AddConstraint(
            model_name='programacionacademica',
            constraint=models.UniqueConstraint(fields=('programa_academico', 'periodo_academico'), name='uk_programa_periodo'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('programacion_academica', 'asignatura', 'nombre'), name='uk_programacion_asignatura_grupo'),
        ),
        migrations.AddConstraint(
            model_name='horariogrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uk_horario_grupo'),
        ),
    ]
