# Generated by Django 5.0.6 on 2026-06-22 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar')], max_length=10)),
                ('modelo_afectado', models.CharField(help_text="Ej. 'Grupo', 'HorarioGrupo'.", max_length=100)),
                ('objeto_id', models.PositiveIntegerField(help_text='Id del registro afectado dentro de su propia tabla.')),
                ('descripcion', models.TextField(help_text='Resumen legible del cambio, ej. "Cambió docente de Laura Martínez a Carlos Gómez".')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción. Se conserva null si el usuario fue eliminado después.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
